### ISSUE TITLE
Implement dynamic schema for analysis types in SONG

### ISSUE THREAD

**Issue by alekspejovic** [overture-stack/SONG#426]
- Schemas for analysis types should be dynamic and easily defined by a data curator without code changes

- Being able to easily create/register new analysis types is critical to our success in ARGO, it's not possible to predict what kind of new scientific data analyses or new experimental data types will emerge. A flexible system would allow us quickly adapt these new analyses and new data types.

On top of our current sequencingRead and variantCall analysis types, examples of some new analysis types we might want to support in the future :

- Read Group Analysis (less permissible than the current sequencingRead analysis)
- Experiment Analysis 
- OxoG filtering
- Reference Genome 

Can refer to gap analysis documentation, describing current and future state in SONG :
https://wiki.oicr.on.ca/pages/viewpage.action?pageId=119286824

Previous investigation ticket :
https://github.com/icgc-argo/roadmap/issues/67

- [x] Technical specs for changes which need to be implemented (2)
https://github.com/icgc-argo/roadmap/issues/78
- [x] Endpoint for users to register a schema, validated against a backbone (2) https://github.com/overture-stack/SONG/issues/427
- [x] Being able to retrieve that schema , extending to be able to list all (2)
https://github.com/overture-stack/SONG/issues/428
- [x] Update a schema (simple change management) (2)
https://github.com/overture-stack/SONG/issues/429
- [x] Update upload functionality to use registered schema (2) #433 
- [x] Implement schema validation for UpdateAnalysis endpoint (2) #448
