### ISSUE TITLE
Identifier Management in SONG

### ISSUE THREAD

**Issue by rtisma** [overture-stack/SONG#490]
https://wiki.oicr.on.ca/pages/viewpage.action?pageId=128222479

- [x] Implement LocalIdService #489  
- ~[ ] Implement Dynamic AuthService #491~ not important right now
- [x] Implement FederatedIdService #492
- [x] Update docker infra #499
- [x] Create Spring Properties and Configuration #493
- [x] Refactor song to use IdService interface #494
- ~[ ] Create argo-file-analysis-id-service for ARGO #495~ no longer needed
- ~[ ] Create Helm chart for argo-file-analysis-id-service #496~ no longer needed
- [x] Release song and deploy to argo-qa/argo-dev #497
- ~[ ] Deploy song to collab and aws #498~ blocked until donors, specimen, sample and files are dynamic
