### ISSUE TITLE
Performance Upgrades

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/SONG#730]
Wiki: https://wiki.oicr.on.ca/pages/viewpage.action?spaceKey=OV&title=Paging+in+Song 

- [ ] Add paging to Song
- [ ] Index from maestro from event instead of song
- [ ] Update queries in song to use stored procedures instead off the current join
